### ISSUE TITLE
run_mp filed

### ISSUE THREAD

**Issue by JRDiana0307** [deepmodeling/reacnetgenerator#2193]
Dear developer,

When I use the command  (reacnetgenerator --type bond -i bonds.reaxc -a C H --nohmm), the following error occurs,   I don't know what is TypeError.I would appreciate it if you could tell me the solution. thank you very mush.

```
2024-04-12 13:15:14,161 - ReacNetGenerator 1.6.12 - ERROR: run_mp failed
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/_detect.py", line 255, in _readstepfunc
    molecules = self._connectmolecule(bond, level)
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/_detect.py", line 188, in _connectmolecule
    mols, bondlists = dps(bond, level)
  File "reacnetgenerator/dps.pyx", line 55, in reacnetgenerator.dps.dps
TypeError: zip argument #1 must support iteration
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/utils.py", line 559, in run_mp
    for item in results:
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/multiprocessing/pool.py", line 354, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: zip argument #1 must support iteration
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/_detect.py", line 255, in _readstepfunc
    molecules = self._connectmolecule(bond, level)
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/_detect.py", line 188, in _connectmolecule
    mols, bondlists = dps(bond, level)
  File "reacnetgenerator/dps.pyx", line 55, in reacnetgenerator.dps.dps
TypeError: zip argument #1 must support iteration
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/bin/reacnetgenerator", line 8, in <module>
    sys.exit(_commandline())
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/commandline.py", line 160, in _commandline
    cell=args.cell,
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/reacnetgen.py", line 270, in runanddraw
    self._process(processthing)
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/reacnetgen.py", line 337, in _process
    _Detect.gettype(self).detect()
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/_detect.py", line 132, in detect
    self._readinputfile()
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/_detect.py", line 152, in _readinputfile
    for molecules, (step, thetimestep) in results:
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/reacnetgenerator/utils.py", line 559, in run_mp
    for item in results:
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/multiprocessing/pool.py", line 354, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/work/home/ac0gjfyzpa/software/anaconda3/envs/ReacNetGenerator/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: zip argument #1 must support iteration
```

**Comment by njzjz** [comment]
Could you provide an example to reproduce the error?
